const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("uk-UA").format(n)+" грн";
const P=window.PRODUCTS||[],C=window.VT_CONFIG||{};
const FALLBACK_IMG="https://cdn.shopify.com/s/files/1/0640/8454/1699/products/natural-linen-duvet-cover-1.jpg?v=1661254233";
function safeImg(url){return String(url||FALLBACK_IMG).replace(/&/g,"&amp;").replace(/"/g,"&quot;")}
function bindImageFallback(root=document){$$("img[data-fallback]",root).forEach(img=>{img.addEventListener("error",()=>{if(img.dataset.fallbackUsed)return;img.dataset.fallbackUsed="1";img.src=FALLBACK_IMG}, {once:true})})}
function card(p){return `<article class="card reveal"><a href="product.html?id=${p.id}"><div class="photo"><img loading="lazy" decoding="async" referrerpolicy="no-referrer" data-fallback src="${safeImg(p.img)}" alt="${p.name}"></div><div class="body"><div class="meta"><span>${p.cat}</span><span>${p.material}</span></div><h3>${p.name}</h3><div class="meta"><span>${p.sizes.join(" · ")}</span><span>${p.group||""}</span></div><div class="row"><span class="price">${money(p.price)}</span><span class="arrow">↗</span></div></div></a></article>`}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");io.unobserve(e.target)}}),{threshold:.08});$$(".reveal:not(.show)").forEach(x=>io.observe(x))}
function setupRails(){["#allRail","#pillowRail","#duvetRail","#linenRail","#coverRail"].forEach(sel=>{const e=$(sel);if(!e)return;let cat=e.dataset.cat;e.innerHTML=P.filter(x=>!cat||x.cat===cat).map(card).join("");bindImageFallback(e)})}
function setupCatalog(){const g=$("#catalogGrid");if(!g)return;let cat="all",size="all",sort="popular";function draw(){let a=[...P];if(cat!=="all")a=a.filter(x=>x.cat===cat);if(size!=="all")a=a.filter(x=>x.sizes.includes(size));if(sort==="cheap")a.sort((x,y)=>x.price-y.price);if(sort==="expensive")a.sort((x,y)=>y.price-x.price);g.innerHTML=a.map(card).join("");bindImageFallback(g);$("#resultCount").textContent=`${a.length} товарів`;observe()}$$(".catFilter").forEach(b=>b.onclick=()=>{$$(".catFilter").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.cat;draw()});$("#sizeFilter")?.addEventListener("change",e=>{size=e.target.value;draw()});$("#sortFilter")?.addEventListener("change",e=>{sort=e.target.value;draw()});const q=new URLSearchParams(location.search).get("cat");if(q){const b=$(`.catFilter[data-cat="${q}"]`);if(b){b.classList.add("active");cat=q}}draw()}
function setupProduct(){
 const d=$("#productDetail"); if(!d)return;
 const id=new URLSearchParams(location.search).get("id"), p=P.find(x=>x.id===id)||P[0];
 let chosen=p.sizes[0],idx=0;
 const gallery=$("#productMediaThumbs"),img=$("#productMainMedia"),vid=$("#productMainVideo"),counter=$("#mediaCounter"),stage=$("#mediaStage");
 const imgs=(p.media?.images||[]).slice(0,6), v=p.media?.video;
 const items=[...imgs.map((s,n)=>({type:"image",src:s,alt:`${p.name} — фото ${n+1}`})),...(v?[{type:"video",src:v.src,poster:v.poster||imgs[0]}]:[])];
 function show(i){if(!items.length)return;idx=(i+items.length)%items.length;const x=items[idx];if(x.type==="video"){img.hidden=true;vid.hidden=false;vid.poster=x.poster||"";vid.src=x.src;vid.load()}else{vid.pause();vid.removeAttribute("src");vid.hidden=true;img.hidden=false;img.src=x.src;img.alt=x.alt}if(counter)counter.textContent=`${idx+1} / ${items.length}`;$$(".media-thumb",gallery).forEach((b,n)=>b.classList.toggle("active",n===idx))}
 if(gallery){gallery.innerHTML="";items.forEach((x,i)=>{const b=document.createElement("button");b.type="button";b.className="media-thumb"+(x.type==="video"?" video-thumb":"");b.setAttribute("aria-label",x.type==="video"?"Відео товару":`Фото ${i+1} товару`);const im=document.createElement("img");im.src=x.type==="video"?(x.poster||imgs[0]):x.src;im.alt="";im.loading="lazy";im.referrerPolicy="no-referrer";b.append(im);b.onclick=()=>show(i);gallery.append(b)})}
 $(".media-prev")?.addEventListener("click",()=>show(idx-1));$(".media-next")?.addEventListener("click",()=>show(idx+1));
 let sx=0;stage?.addEventListener("touchstart",e=>sx=e.changedTouches[0].clientX,{passive:true});stage?.addEventListener("touchend",e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)show(idx+(dx<0?1:-1))},{passive:true});
 vid?.addEventListener("error",()=>{vid.hidden=true;img.hidden=false;img.src=imgs[0]||""});
 show(0);
 d.innerHTML=`<div class="detailInfo"><span class="eyebrow">${p.cat}</span><h1>${p.name}</h1><p class="muted">${p.desc}</p><div class="price">${money(p.price)}</div><p class="eyebrow" style="margin-top:28px">РОЗМІР</p><div class="sizes">${p.sizes.map((s,i)=>`<button class="size ${i===0?"active":""}" data-size="${s}">${s}</button>`).join("")}</div><p class="muted">Матеріал: ${p.material}<br>Доставка: Нова Пошта або Укрпошта</p><button class="btn dark" id="add" style="width:100%">Додати в кошик →</button></div>`;
 $$(".size",d).forEach(b=>b.onclick=()=>{$$(".size",d).forEach(x=>x.classList.remove("active"));b.classList.add("active");chosen=b.dataset.size});$("#add",d).onclick=()=>addCart(p,chosen);
}
let cart=JSON.parse(localStorage.getItem("vt_cart")||"[]");
function addCart(p,size){let x=cart.find(i=>i.id===p.id&&i.size===size);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:p.price,img:p.img,size,qty:1});localStorage.setItem("vt_cart",JSON.stringify(cart));openCart()}
function openCart(){const d=$("#drawer");if(!d)return;d.classList.add("open");renderCart();bindImageFallback(document)}
function renderCart(){const box=$("#cartItems");if(!box)return;box.innerHTML=cart.length?cart.map((x,i)=>`<div class="cartItem"><img loading="lazy" decoding="async" referrerpolicy="no-referrer" data-fallback src="${safeImg(x.img)}" alt=""><div><b>${x.name}</b><div class="muted">${x.size} · ${money(x.price)}</div><div>${x.qty} шт.</div></div><button class="icon" onclick="removeItem(${i})">×</button></div>`).join(""):`<p class="muted">Кошик порожній.</p>`;const t=cart.reduce((s,x)=>s+x.price*x.qty,0);$("#cartTotal").textContent=money(t);$$(".count").forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0))}
function removeItem(i){cart.splice(i,1);localStorage.setItem("vt_cart",JSON.stringify(cart));renderCart();bindImageFallback(document)}
function closeCart(){$("#drawer")?.classList.remove("open")}
function setupCart(){$("#cartOpen")?.addEventListener("click",openCart);$("#cartClose")?.addEventListener("click",closeCart);$("#drawer")?.addEventListener("click",e=>{if(e.target.id==="drawer")closeCart()});renderCart();bindImageFallback(document)}
async function sendOrder(e){e.preventDefault();const fd=new FormData(e.target),data=Object.fromEntries(fd.entries());data.cart=cart;const btn=e.submitter;btn.disabled=true;btn.textContent="Відправляємо…";try{if(!C.ORDER_ENDPOINT)throw new Error("endpoint");await fetch(C.ORDER_ENDPOINT,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)});$("#success").classList.add("show");e.target.style.display="none";localStorage.removeItem("vt_cart");cart=[]}catch(err){alert("Не вдалося відправити заявку. Перевірте Google Apps Script.");}finally{btn.disabled=false;btn.textContent="Відправити замовлення →"}}
document.addEventListener("DOMContentLoaded",()=>{setupRails();setupCatalog();setupProduct();setupCart();$$("[data-order-form]").forEach(f=>f.addEventListener("submit",sendOrder));$$(".faqItem").forEach(x=>x.onclick=()=>x.classList.toggle("open"));observe()});
